# Dependencies
markdown:           kramdown
highlighter:        highlighter

# Permalinks
permalink:          pretty

# Server
source:             docs
destination:        _gh_pages
host:               0.0.0.0
port:               9001
baseurl:
url:                http://localhost:9001
encoding:           UTF-8
